In [1]:
import numpy as np
import pandas as pd
import gensim
from gensim.models import Word2Vec, KeyedVectors
from gensim.models import FastText
from tqdm import tqdm
import ast

In [2]:
data = pd.read_csv('./Original_data/taiwan_charity_news_keywords.csv', encoding='UTF-8')

In [3]:
data.head(1)

Index      Date                       Title         Media  \
0      1  2017/1/9  視障弟月薪僅800？勞工局：是見習生獎金，不是薪資。  ETtoday_News   

                                             Content  Related Topic_test  \
0  一名雙眼失明的闕小弟因為父親入獄、肢體障礙的母親也遠在高雄，只剩他和弟弟2人在北部生活，只好...        1          0   

  News_tags Stance_label                                           Seg_list  \
0         0      neutral  一 名 雙眼 失明 闕 小弟 父親 入獄 肢體 障礙 母親 遠 高雄 剩 弟弟 2 人 北部...   

   ...                                         Keyword_K8  \
0  ...  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                          Keyword_K9  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K10  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K11  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K12  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K18  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K20  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K25  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K30  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K35  
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...  

[1 rows x 25 columns]

In [4]:
# 將Dataframe裡面狀似List的String還原回List
def extract_list(df, column_name):
    list_strs = df[column_name].tolist()
    lists_ = [ast.literal_eval(list_str) for list_str in list_strs]
    return lists_

In [5]:
key20 = extract_list(data, 'Keyword_K20')
key25 = extract_list(data, 'Keyword_K25')
key30 = extract_list(data, 'Keyword_K30')
key35 = extract_list(data, 'Keyword_K35')

In [8]:
x = key25[0]
if isinstance(x, list):
    print("yes")
else:
    print("no")
print(x)
print(len(x))

yes
['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', '擔任', '協助', '目前', '就業', '工作', '表示', '安排', '口香糖', '身障', '見習生', '轉業', '未來', '800', '單位', '月薪', '職場', '障礙', '10月']
25


In [9]:
#中文維基詞向量-路徑
# zhwiki_path = r'D:\Code\NTUT_Thesis\model_data\zhwiki\wiki.zh.vector'
#fastText Facebook 20萬字訓練詞向量-路徑
fasttext_path = r'D:\ellom\working\NTUT_Thesis\wordvec_model\cc.zh.300.vec'

In [10]:
# 載入詞向量function
def load_fasttext():
        print('loading word embeddings...')
        embeddings_index = {}
        f = open(fasttext_path, encoding='utf-8')
        for line in tqdm(f):
                values = line.strip().rsplit(' ')
                word = values[0]
                coefs = np.asarray(values[1:], dtype='float32')
                embeddings_index[word] = coefs
        f.close()
        print('found %s word vectors' % len(embeddings_index))
        return embeddings_index

In [11]:
# 載入詞向量
model = load_fasttext()
#model的資料結構是dictionary

loading word embeddings...


2000001it [02:19, 14316.69it/s]

found 2000000 word vectors


In [21]:
vec = model['視障']
print(vec.shape)
print(vec)

(300,)
[-1.5040e-01 -3.9000e-01  2.6000e-01  2.7670e-01 -2.1450e-01 -7.6100e-02
 -5.9200e-01 -1.6080e-01  3.7380e-01  2.9700e-01  9.2000e-02  4.2750e-01
 -2.8560e-01 -6.5800e-02  2.0620e-01 -3.4460e-01  2.8060e-01 -2.0880e-01
  2.2100e-01 -2.4500e-02  2.1840e-01 -1.8780e-01  1.8080e-01 -3.0930e-01
 -5.4700e-02  2.9680e-01  7.9600e-02  1.6700e-01  8.8300e-02  2.7000e-01
 -1.3920e-01  6.7300e-02  3.4120e-01 -3.5320e-01 -6.5930e-01  2.0300e-01
 -3.1740e-01  4.7500e-02 -1.3100e-01 -9.4400e-02  7.3500e-02 -8.5100e-02
 -1.0800e-01 -1.8140e-01 -2.7840e-01  2.1710e-01 -2.7060e-01  6.8100e-02
  9.8900e-02 -3.2600e-02  2.7010e-01 -2.7040e-01 -5.4900e-02  2.4130e-01
 -4.2800e-02 -2.6310e-01  8.9400e-02 -2.7600e-02 -2.2090e-01  4.8440e-01
 -2.1410e-01  8.2700e-02  1.1580e-01 -3.0720e-01 -2.9490e-01 -3.1590e-01
  2.6500e-02  4.1790e-01  7.0990e-01  1.3640e-01 -3.5080e-01  1.2620e-01
  2.0900e-01 -3.8500e-02  4.0610e-01  1.5360e-01  1.1680e-01 -9.1400e-02
  1.8170e-01  1.0420e-01 -6.1340e-01  5.2500

In [13]:
def convert_vec(lists_of_keywords, model):
    vectors = []
    # Loop through each list of keywords in 'lists_of_keywords', and convert each keyword into a word vector using the FastText model:
    for doc_keywords in lists_of_keywords:
        doc_vectors = []
        for keyword in doc_keywords:
            # Use the FastText model to get the word vector for each keyword
            try:
                vector = model[keyword]
            except KeyError:
                vector = np.zeros(300)
            doc_vectors.append(vector)
        # Convert the list of vectors for this document into a numpy array
        doc_vectors = np.array(doc_vectors)
        vectors.append(doc_vectors)
    return vectors

In [22]:
vec20 = convert_vec(key20, model)
vec25 = convert_vec(key25, model)
vec30 = convert_vec(key30, model)
vec35 = convert_vec(key35, model)

In [19]:
print(len(vec30))
print(vec30[0].shape)
print(vec30[0])


445
(30, 300)
[[-0.116  -0.1135  0.061  ...  0.012   0.0984  0.0661]
 [-0.1222 -0.2408  0.2029 ... -0.0839  0.0375  0.193 ]
 [-0.0424  0.1416  0.3192 ... -0.0804  0.0844  0.0398]
 ...
 [-0.3496  0.1257  0.3653 ...  0.068   0.1968  0.1238]
 [ 0.0044  0.3534  0.0683 ...  0.0485  0.3417  0.0415]
 [ 0.1021  0.0328  0.4115 ...  0.0505 -0.0959  0.1822]]


In [20]:
print(vec30)

[array([[-0.116 , -0.1135,  0.061 , ...,  0.012 ,  0.0984,  0.0661],
       [-0.1222, -0.2408,  0.2029, ..., -0.0839,  0.0375,  0.193 ],
       [-0.0424,  0.1416,  0.3192, ..., -0.0804,  0.0844,  0.0398],
       ...,
       [-0.3496,  0.1257,  0.3653, ...,  0.068 ,  0.1968,  0.1238],
       [ 0.0044,  0.3534,  0.0683, ...,  0.0485,  0.3417,  0.0415],
       [ 0.1021,  0.0328,  0.4115, ...,  0.0505, -0.0959,  0.1822]],
      dtype=float32), array([[-0.3529    , -0.0425    ,  0.37619999, ..., -0.0438    ,
        -0.1234    ,  0.034     ],
       [-0.0385    , -0.2054    ,  0.44859999, ..., -0.0864    ,
         0.142     ,  0.219     ],
       [-0.1771    ,  0.0388    ,  0.4542    , ...,  0.26820001,
        -0.0945    , -0.0071    ],
       ...,
       [-0.3479    , -0.29449999,  0.0623    , ..., -0.0553    ,
        -0.0871    , -0.1138    ],
       [ 0.0546    ,  0.1002    , -0.0975    , ..., -0.49689999,
        -0.2156    , -0.1193    ],
       [-0.0122    , -0.16949999,  0.4587999

In [23]:
def average_vectors(vectors):
    averaged_vectors = []
    # Loop through each vector array in 'vectors', and compute the average vector
    for vector_array in vectors:
        # Compute the mean vector along axis 0
        averaged_vector = np.mean(vector_array, axis=0)
        # Reshape the vector to have shape (1, 300)
        averaged_vector = np.reshape(averaged_vector, (1, -1))
        # Append the averaged vector to the list
        averaged_vectors.append(averaged_vector)

    return averaged_vectors

In [37]:
vec20_avg = average_vectors(vec20)
vec25_avg = average_vectors(vec25)
vec30_avg = average_vectors(vec30)
vec35_avg = average_vectors(vec35)

In [25]:
print(len(vec30_avg))
print(vec30_avg[0].shape)
print(vec30_avg[0])

445
(1, 300)
[[-3.50966640e-02 -4.30600010e-02  3.37619960e-01  1.11586668e-01
  -2.78633349e-02  4.35299948e-02 -3.17133404e-02 -1.13633340e-02
   1.22383326e-01 -1.04666746e-03  4.22566682e-02  6.91033453e-02
   4.50833328e-02 -5.69599979e-02 -5.21500036e-02  4.39833365e-02
   1.55600011e-02  1.14233308e-02  2.50899997e-02  4.14766669e-02
   1.50933331e-02 -3.47400047e-02 -3.68533358e-02 -1.19066676e-02
   1.37900012e-02 -1.40000065e-03 -4.23100032e-02  3.02733257e-02
  -1.30500002e-02  5.42666726e-02  4.83133346e-02  1.11633362e-02
   2.39500012e-02 -3.65699977e-02 -8.43133256e-02  1.13400007e-02
   1.73733309e-02 -9.18366686e-02  9.63999983e-03  3.43666710e-02
  -2.21533310e-02  7.30000960e-04  9.33966711e-02 -3.61933336e-02
  -3.31666716e-03 -6.99977099e-05 -3.43699962e-01 -1.86433326e-02
  -3.00666597e-03 -1.06900036e-02  3.36933248e-02 -2.29800027e-02
   3.99266630e-02 -7.77166560e-02 -1.16496675e-01  6.76500052e-02
   4.77633364e-02  2.40000011e-03  5.86533397e-02  4.00633365e-

In [26]:
print(vec30_avg)

[array([[-3.50966640e-02, -4.30600010e-02,  3.37619960e-01,
         1.11586668e-01, -2.78633349e-02,  4.35299948e-02,
        -3.17133404e-02, -1.13633340e-02,  1.22383326e-01,
        -1.04666746e-03,  4.22566682e-02,  6.91033453e-02,
         4.50833328e-02, -5.69599979e-02, -5.21500036e-02,
         4.39833365e-02,  1.55600011e-02,  1.14233308e-02,
         2.50899997e-02,  4.14766669e-02,  1.50933331e-02,
        -3.47400047e-02, -3.68533358e-02, -1.19066676e-02,
         1.37900012e-02, -1.40000065e-03, -4.23100032e-02,
         3.02733257e-02, -1.30500002e-02,  5.42666726e-02,
         4.83133346e-02,  1.11633362e-02,  2.39500012e-02,
        -3.65699977e-02, -8.43133256e-02,  1.13400007e-02,
         1.73733309e-02, -9.18366686e-02,  9.63999983e-03,
         3.43666710e-02, -2.21533310e-02,  7.30000960e-04,
         9.33966711e-02, -3.61933336e-02, -3.31666716e-03,
        -6.99977099e-05, -3.43699962e-01, -1.86433326e-02,
        -3.00666597e-03, -1.06900036e-02,  3.36933248e-

In [41]:
#Save NPZ
data = {'averaged_vectors': np.array(vec35_avg)}
# Save the dictionary to a compressed '.npz' archive file

np.savez_compressed('vec35_avg.npz', **data)
    

In [64]:
def load_npz_file(filepath):
    # Load the numpy array from the .npz file
    with np.load(filepath, allow_pickle=True) as data:
        for key in data.keys():
            arr = data[key]
            break
    return arr

In [71]:
filepath = r'D:\ellom\working\NTUT_Thesis\vec30_avg.npz'

In [72]:
test = load_npz_file(filepath)

In [73]:
print(len(test))
print(test[0].shape)
print(test[0])

445
(1, 300)
[[-3.50966640e-02 -4.30600010e-02  3.37619960e-01  1.11586668e-01
  -2.78633349e-02  4.35299948e-02 -3.17133404e-02 -1.13633340e-02
   1.22383326e-01 -1.04666746e-03  4.22566682e-02  6.91033453e-02
   4.50833328e-02 -5.69599979e-02 -5.21500036e-02  4.39833365e-02
   1.55600011e-02  1.14233308e-02  2.50899997e-02  4.14766669e-02
   1.50933331e-02 -3.47400047e-02 -3.68533358e-02 -1.19066676e-02
   1.37900012e-02 -1.40000065e-03 -4.23100032e-02  3.02733257e-02
  -1.30500002e-02  5.42666726e-02  4.83133346e-02  1.11633362e-02
   2.39500012e-02 -3.65699977e-02 -8.43133256e-02  1.13400007e-02
   1.73733309e-02 -9.18366686e-02  9.63999983e-03  3.43666710e-02
  -2.21533310e-02  7.30000960e-04  9.33966711e-02 -3.61933336e-02
  -3.31666716e-03 -6.99977099e-05 -3.43699962e-01 -1.86433326e-02
  -3.00666597e-03 -1.06900036e-02  3.36933248e-02 -2.29800027e-02
   3.99266630e-02 -7.77166560e-02 -1.16496675e-01  6.76500052e-02
   4.77633364e-02  2.40000011e-03  5.86533397e-02  4.00633365e-

In [ ]:
# 若未知詞使用『全零向量』填充，這邊製作全零向量
# vec_size = next(iter(model.items()))[1]
# unknown = np.zeros((vec_size.shape), dtype=np.float32)
# print(unknown.shape)
# print(unknown)

In [ ]:
#好...我們現在有一組keyword存在List裡面
#['視障', '愛盲', '林佳臻', '基金會', '媽媽', '家庭', '成為', '看見', '今年', '母親', '表示', '支持', '女性', '龍鳳胎', '故事']
#那麼我們把這個List裡面的所有元素依序丟入model裡面，每個元素會被換算出一組300維的向量。
#那個(300,0)x15的向量該怎麼儲存比較好呢？List嗎?這樣就會是一個由15組array為元素的List，是這樣嗎??
#對了，某些專有名詞或人名沒有被訓練在word vector裡面...所以...要怎麼辦呢?
#某些討論有提到，(1)未知詞使用『模型平均向量』填充  (2)未知詞使用『全零向量』填充
#假設是這樣的話就這樣寫:

# ldavec_list = [] #由15組詞向量作為元素的List
# unknown_list = [] #把未知詞都另外添加到其他List，事後回來檢查有沒有重要詞是未知詞

# for i in lda_keywords[0]:
#     if i in model.keys(): #檢查詞有沒有被訓練在模型裡面，沒有就是未知詞
#         ldavec_list.append(model[i])
#     else:
#         ldavec_list.append(unknown)
#         unknown_list.append(i)
# print(len(ldavec_list)) #檢查由15組詞向量作為元素的List的長度
# print(ldavec_list[0]) #檢查第1個向量
# print(unknown_list) #檢查未知詞名單