In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [5]:
data = pd.read_csv('./Original_data/taiwan_charity_news_keywords.csv', encoding='UTF-8')

In [6]:
data.head(1)

Index      Date                       Title         Media  \
0      1  2017/1/9  視障弟月薪僅800？勞工局：是見習生獎金，不是薪資。  ETtoday_News   

                                             Content  Related Topic_test  \
0  一名雙眼失明的闕小弟因為父親入獄、肢體障礙的母親也遠在高雄，只剩他和弟弟2人在北部生活，只好...        1          0   

  News_tags Stance_label                                           Seg_list  \
0         0      neutral  一 名 雙眼 失明 闕 小弟 父親 入獄 肢體 障礙 母親 遠 高雄 剩 弟弟 2 人 北部...   

   ...                                         Keyword_K8  \
0  ...  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                          Keyword_K9  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K10  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K11  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K12  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K18  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K20  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K25  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K30  \
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...   

                                         Keyword_K35  
0  ['庇護工場', '勞工局', '小弟', '薪資', '愛盲', '當時', '生活', ...  

[1 rows x 25 columns]

In [7]:
data['Stance_label'].value_counts()

neutral      201
unrelated    159
proactive     74
hostile       11
Name: Stance_label, dtype: int64

In [8]:
Stance_label = data['Stance_label'].tolist()

In [9]:
print(Stance_label)

['neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'proactive', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'proactive', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'hostile', 'hostile', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'proactive', 'proactive', 'proactive', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'hostile', 'hostile', 'hostile', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'proactive', 'proactive', 'neutral', 'proactive', 'neutral', 'proactive', 'n

In [10]:
# Frequency Encoding
label_freq_map = data['Stance_label'].value_counts().to_dict()
print(label_freq_map)
freq_stance_labels = np.array(list(map(lambda x: label_freq_map.get(x, 0), Stance_label)))
freq_stance_labels = freq_stance_labels.reshape(445,1)
print(freq_stance_labels.shape)
print(freq_stance_labels)

{'neutral': 201, 'unrelated': 159, 'proactive': 74, 'hostile': 11}
(445, 1)
[[201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [ 74]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [ 74]
 [201]
 [201]
 [201]
 [201]
 [201]
 [ 11]
 [ 11]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [ 74]
 [ 74]
 [ 74]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [ 11]
 [ 11]
 [ 11]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [201]
 [ 74]
 [ 74]
 [201]
 [ 74]
 [201]
 [ 74]
 [201]
 [ 74]
 [201]
 [ 74]
 [ 74]
 [201]
 [ 74]
 [ 74]
 [ 74]
 [201]
 [201]
 [ 74]
 [201]
 [201]
 [201]
 [201]
 [201]
 [ 74]
 [201]
 [201]
 [ 74]
 [ 74]
 [201]
 [201]
 [201]
 [201]
 [201]
 [ 74]
 [ 74]
 [ 74]
 [ 74]
 [ 74]
 [ 74]
 [201]
 [201]
 [201]
 [201]
 [201]
 [ 74]
 [ 74]
 [ 74]
 [ 74]
 [ 74]


In [11]:
#Save freq_stance_label
freq_stance = {'freq_stance_labels': freq_stance_labels}
# Save the dictionary to a compressed '.npz' archive file
np.savez_compressed('./vec_data/freq_stance_labels.npz', **freq_stance)

In [12]:
# One-Hot Encoding
ohe = OneHotEncoder()
oh_stance_labels = ohe.fit_transform(data.Stance_label.values.reshape(-1,1)).toarray()

In [13]:
print(oh_stance_labels)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [14]:
#Save oh_stance_labels 
oh_stance = {'oh_stance_labels': oh_stance_labels}
# Save the dictionary to a compressed '.npz' archive file
np.savez_compressed('./vec_data/oh_stance_labels.npz', **oh_stance)

In [15]:
# Label Encoding
le = LabelEncoder()
le_stance_labels = le.fit_transform(data.Stance_label.values.reshape(-1,1))

c:\Users\ellom\miniconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [16]:
print(le_stance_labels)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 2 1 2 1 2 1 2 1 2 2 1 2 2 2 1 1 2 1 1 1 1 1 2 1 1 2 2
 1 1 1 1 1 2 2 2 2 2 2 1 1 1 1 1 2 2 2 2 2 2 2 2 1 1 1 1 1 2 2 1 2 1 1 1 1
 1 1 1 1 1 1 1 2 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 2 2
 1 1 2 1 1 1 2 2 2 2 1 1 2 1 1 2 2 2 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 0 0 0 0 0 1 2 2 1 1 2 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 1 1 2 1 1 1
 2 1 2 2 2 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3]


In [20]:
#Save le_stance_labels 
le_stance = {'le_stance_labels': le_stance_labels}
# Save the dictionary to a compressed '.npz' archive file
np.savez_compressed('./vec_data/le_stance_labels.npz', **le_stance)

In [18]:
def load_npz_file(filepath):
    # Load the numpy array from the .npz file
    with np.load(filepath, allow_pickle=True) as data:
        for key in data.keys():
            arr = data[key]
            break
    return arr

In [21]:
# test_freq = load_npz_file('freq_stance_labels.npz')
test_le = load_npz_file('le_stance_labels.npz')

In [22]:
print(test_le.shape)
print(test_le)

(445,)
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 2 1 2 1 2 1 2 1 2 2 1 2 2 2 1 1 2 1 1 1 1 1 2 1 1 2 2
 1 1 1 1 1 2 2 2 2 2 2 1 1 1 1 1 2 2 2 2 2 2 2 2 1 1 1 1 1 2 2 1 2 1 1 1 1
 1 1 1 1 1 1 1 2 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 2 2
 1 1 2 1 1 1 2 2 2 2 1 1 2 1 1 2 2 2 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 0 0 0 0 0 1 2 2 1 1 2 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 1 1 2 1 1 1
 2 1 2 2 2 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3]
