In [31]:
import numpy as np

In [35]:
#Load first key in npz
def load_npz_file(filepath):
    # Load the numpy array from the .npz file
    with np.load(filepath, allow_pickle=True) as data:
        for key in data.keys():
            arr = data[key]
            break
    return arr

#Average method: average (30, 300) vectors along with axis 0
def average_vectors(vectors):
    averaged_vectors = []
    # Loop through each vector array in 'vectors', and compute the average vector
    for vector_array in vectors:
        # Compute the mean vector along axis 0
        averaged_vector = np.mean(vector_array, axis=0)
        # Reshape the vector to have shape (1, 300)
        averaged_vector = np.reshape(averaged_vector, (1, -1))
        # Append the averaged vector to the list
        averaged_vectors.append(averaged_vector)
    return averaged_vectors

#Sum method: sum (30, 300) vectors along with axis 0
def sum_vectors(vectors):
    summed_vectors = []
    # Loop through each vector array in 'vectors', and compute the sum vector
    for vector_array in vectors:
        # Compute the summed vector along axis 0
        summed_vector = np.sum(vector_array, axis=0)
        # Reshape the vector to have shape (1, 300)
        summed_vector = np.reshape(summed_vector, (1, -1))
        # Append the averaged vector to the list
        summed_vectors.append(summed_vector)
    return summed_vectors

In [38]:
vec20 = load_npz_file(r'D:\Code\NTUT_Thesis\vec_data\vec20.npz')
vec25 = load_npz_file(r'D:\Code\NTUT_Thesis\vec_data\vec25.npz')
vec30 = load_npz_file(r'D:\Code\NTUT_Thesis\vec_data\vec30.npz')
vec35 = load_npz_file(r'D:\Code\NTUT_Thesis\vec_data\vec35.npz')

In [39]:
print(len(vec25))
print(vec25[0].shape)
print(vec25[0])

445
(25, 300)
[[-0.116  -0.1135  0.061  ...  0.012   0.0984  0.0661]
 [-0.1222 -0.2408  0.2029 ... -0.0839  0.0375  0.193 ]
 [-0.0424  0.1416  0.3192 ... -0.0804  0.0844  0.0398]
 ...
 [ 0.0613  0.0329  0.3212 ... -0.0373  0.0689 -0.0612]
 [-0.0252 -0.2046  0.6629 ...  0.1998 -0.0218 -0.1348]
 [ 0.0122 -0.0083  0.2147 ...  0.0316 -0.008   0.0334]]


In [40]:
vec20_sum = sum_vectors(vec20)
vec25_sum = sum_vectors(vec25)
vec30_sum = sum_vectors(vec30)
vec35_sum = sum_vectors(vec35)

In [21]:
print(len(vec20_sum))
print(vec20_sum[0].shape)
print(vec20_sum[0])

445
(1, 300)
[[-6.78000033e-01 -1.20420003e+00  6.85469961e+00  1.59250009e+00
  -6.99300051e-01  9.35099959e-01 -6.31000042e-01 -5.36700010e-01
   1.86039996e+00  1.57000005e-01  8.83899987e-01  2.13280010e+00
   6.24800026e-01 -9.35900033e-01 -7.55500019e-01  6.58100009e-01
   3.47300053e-01  2.55999953e-01 -8.18000436e-02  5.76399982e-01
  -3.27899963e-01 -4.55100000e-01 -2.20900074e-01 -4.23900038e-01
  -2.61999667e-02  1.32599980e-01 -6.42699957e-01  9.01799858e-01
  -4.16299999e-01  9.71000135e-01  7.18800008e-01 -9.37999412e-02
   5.08300006e-01 -1.08310008e+00 -2.65410018e+00  1.39000174e-02
   6.13499999e-01 -1.72910011e+00 -2.65100002e-01  6.56300008e-01
  -8.05499971e-01  3.43300015e-01  1.73740029e+00 -4.11000140e-02
  -4.27000016e-01 -5.96499860e-01 -6.94309998e+00  4.45999950e-02
  -1.27499968e-01 -3.42800051e-01  7.57999897e-01 -8.76100063e-01
   5.03299952e-01 -2.20309997e+00 -2.30280018e+00  1.39300013e+00
   4.50399995e-01  3.91999930e-02  1.29859996e+00  1.20050001e+

In [43]:
#Save NPZ
data = {'vec35_sum': np.array(vec35_sum)}
# Save the dictionary to a compressed '.npz' archive file
np.savez_compressed('./vec_data/vec35_sum.npz', **data)